id = "autumnal-marscape"
name = "Autumnal Marscape"
version = "0.0.1"
schema_version = 1
authors = ["Lilyyy411"]
description = "Feel immersed in the Martian landscape with this festive pink and orange dark Zed theme"
repository = "https://github.com/lilyyy411/autumnal-marscape"
